[server]
address = "localhost"
port = 8502

[browser]
serverAddress = "localhost"
serverPort = 8502
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 