services:
  - type: web
    name: risk-analyst
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/init_risk_db.py
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Updated for better compatibility
      # ⚠️ DATABASE_URL and RISK_DATABASE_URL should be set in Render.com dashboard
      # ⚠️ Remove hardcoded credentials for security 