services:
  - type: web
    name: memorymap-api
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/test_db_connection.py
      python backend/direct_db_init.py
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: memorymap-db
          property: connectionString

databases:
  - name: memorymap-db
    databaseName: memorymap
    ipAllowList: []
    plan: free 