[server]
address = "localhost"
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
serverPort = 8502
gatherUsageStats = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#424242"
font = "sans serif" 